### ISSUE TITLE
Help needed for party planning

### ISSUE THREAD

**Issue by joeyklee** [joeyklee/friendly-collab-party#2]
# Party Planning

I need help with the following tasks - please add your contributions to their own individual file (e.g. food.md, invitations.md, etc):
- [x] Food
- [x] Invitations
- [x] Venue
- [x] Entertainment
- [x] Music Playlist

**Comment by stephwright** [comment]
Hi @joeyklee!  I'd love to help out!  Where do you need the most help?

**Comment by joeyklee** [comment]
Hi Steph so nice to meet you _virtually_ - I could really use some help with the costumes - they are all the rage

**Comment by stephwright** [comment]
That's awesome!  I used to be a theater major.  I :heart: costumes!  I'll start on that issue.
