### ISSUE TITLE
Help Needed  - Food for party

### ISSUE THREAD

**Issue by joeyklee** [joeyklee/friendly-collab-party#4]
I'm hopelessly confused on what kind of food we should have at this party. 

I want to be conscious of dietary restrictions (e.g. vegan, gluten free, etc) but I also want tasty options for the omnivores. 

Can someone help me?
## Contribute:
- please add your contribution to the root directory of the repo
- the file should be called `FOOD.md`
- include images of the objects! 
- Gif's are encouraged!

**Comment by siljahund** [comment]
Hi I can help with food, I will come up with some ideas and share. Silja

**Comment by ihawth81github** [comment]
Hi Joey, I like food, enjoy cooking and would be happy to help with this.

**Comment by Lauramorillas** [comment]
Hi guys, I am a great cook. My speciality is Spanish food if you are interested in advice?
Please feel free to ask me for help about this.

Best!

**Comment by siljahund** [comment]
I added lots of ideas for CAKES!

**Comment by joeyklee** [comment]
@siljahund - Great! thanks so much. Food and beverages are so crucial!
