### ISSUE TITLE
Help Needed - Venue

### ISSUE THREAD

**Issue by joeyklee** [joeyklee/friendly-collab-party#5]
I've got a party of 30 - 40 people and finding a venue has been a nightmare. My parents said they were going to be away this weekend, but their trip got canceled because of a terrible hurricane, so my plans are ruined! 

Anyone have any suggestions? 

It would be great if we had:
- [ ] a link to the address, 
- [ ] maybe a screenshot of the map,
- [ ] and possible transport options to get there

Thanks! How am I going to be the coolest kid in school without a place to host this party! Ahhhh!
## Contribute:
- please add your contribution to the root directory of the repo
- the file should be called `VENUE.md`
- include images of the objects! 
- Gif's are encouraged!

**Comment by emefie** [comment]
Hey Joey!  I got this!

**Comment by joeyklee** [comment]
Hi @emefie - Super! looking forward.
