### ISSUE TITLE
Help Needed - Entertainment

### ISSUE THREAD

**Issue by joeyklee** [joeyklee/friendly-collab-party#6]
Ahhh, planning a party is so tough! How am I expected to keep 30 - 40 people entertained?

Can you help me plan some:
- [ ] Music
- [ ] Speakers - e.g. inspirational people (e.g. Kaitlin Thaney from the Mozilla Science Lab, or Jenny Bryan at UBC)
- [ ] Activities - dance off anyone?

What do young people do these days at parties anyways?
## Contribute:
- please add your contribution to the root directory of the repo
- the file should be called `ENTERTAINMENT.md`
- include images of the objects! 
- Gif's are encouraged!

**Comment by DeirdreLoughnan** [comment]
Hey Joey! 
I have an idea for an activity! 

:smiley:
