### ISSUE TITLE
Help Needed - Decorations

### ISSUE THREAD

**Issue by joeyklee** [joeyklee/friendly-collab-party#7]
I didn't even think about decorations, but who wants to go to a party that **isn't** well decorated.... NO ONE, that's who. 

Please help me think up decorations for this party. It can be anything from laser lights, to fog machines, to slip-and-slides. Be creative, but I have no clue! 
## Contribute:
- please add your contribution to the root directory of the repo
- the file should be called `DECORATIONS.md`
- include images of the objects! 
- Gif's are encouraged!

**Comment by KellySchultzUBC** [comment]
Hi Joey! We can contribute some info on decorations, if you'd like!

**Comment by joeyklee** [comment]
Hi @KellySchultzUBC  !! Thanks so much for contacting me - I will keep my eye out for a pull request. 

🌈
