### ISSUE TITLE
Help Needed - Costumes

### ISSUE THREAD

**Issue by joeyklee** [joeyklee/friendly-collab-party#8]
It turns out that costume parties are a thing these days, but I missed the memo. 

Anyone have any clues about costume options I could provide or themes for costumes?
## Contribute:
- please add your contribution to the root directory of the repo
- the file should be called `COSTUMES.md`
- include images of the objects! 
- Gif's are encouraged!

**Comment by cameronshunter** [comment]
Hey Joey can I help out with costumes to? I've got some good ideas!

**Comment by joeyklee** [comment]
@cameronshunter  Thanks so much this party is going to be great ❤️
